# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bart <- function(x_train, y, x_test, x_cut, n_tree, n_mcmc, n_burn, n_min_size, tau, mu, tau_mu, alpha, beta, a_tau, d_tau) {
    .Call('_rcppGPBART_bart', PACKAGE = 'rcppGPBART', x_train, y, x_test, x_cut, n_tree, n_mcmc, n_burn, n_min_size, tau, mu, tau_mu, alpha, beta, a_tau, d_tau)
}

test_grow_tree <- function(x_train, x_test, y_train, x_cut, alpha, beta, node_min_size, tau, tau_mu) {
    invisible(.Call('_rcppGPBART_test_grow_tree', PACKAGE = 'rcppGPBART', x_train, x_test, y_train, x_cut, alpha, beta, node_min_size, tau, tau_mu))
}

test_prune_tree <- function(x_train, x_test, y_train, x_cut, alpha, beta, node_min_size, tau, tau_mu) {
    invisible(.Call('_rcppGPBART_test_prune_tree', PACKAGE = 'rcppGPBART', x_train, x_test, y_train, x_cut, alpha, beta, node_min_size, tau, tau_mu))
}

test_change_tree <- function(x_train, x_test, y_train, x_cut, alpha, beta, node_min_size, tau, tau_mu) {
    invisible(.Call('_rcppGPBART_test_change_tree', PACKAGE = 'rcppGPBART', x_train, x_test, y_train, x_cut, alpha, beta, node_min_size, tau, tau_mu))
}

matrix_leak <- function(x_train) {
    .Call('_rcppGPBART_matrix_leak', PACKAGE = 'rcppGPBART', x_train)
}

