# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test_grow_tree <- function(x_train, x_test, y_train, x_cut, alpha, beta, node_min_size, tau, tau_mu) {
    invisible(.Call('_rcppGPBART_test_grow_tree', PACKAGE = 'rcppGPBART', x_train, x_test, y_train, x_cut, alpha, beta, node_min_size, tau, tau_mu))
}

